### PR TITLE
JSON documentation

### PR DESCRIPTION
**Pull request by sebastiaanfranken**
The first (rough) version of my JSON documentation, referencing #177

### CODE REVIEW

**Comment by domferr** [comment]
Hey, thank you so much for your contributions! I gave a quick look and it seems very well made. Because of this, I'm changing the target branch to the next release's branch (v15.1). I'll take some time to read it carefully and then merge, thank you once again!

**Comment by sebastiaanfranken** [comment]
The spelling should probably be checked. English is not my native language, and it might show... 
Glad you like it though! It was really interesting writing it!

**Comment by domferr** [comment]
Thank you once again @sebastiaanfranken. I'd like to know if I have your permission to publicly cite your GitHub profile in the next release notes! Let me know and feel free to tell me 'no', that's not a problem :smile:

**Comment by sebastiaanfranken** [comment]
> Thank you once again @sebastiaanfranken. I'd like to know if I have your permission to publicly cite your GitHub profile in the next release notes! Let me know and feel free to tell me 'no', that's not a problem 😄

That's fine by me!

**Pull request merged**
